import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./customComponents/footer";
import Navbar from "./customComponents/navbar";
// import { revalidate } from "./(roots)/page";
import { Toaster } from "react-hot-toast";
import { Separator } from "@/components/ui/separator";
import { ClerkProvider } from '@clerk/nextjs'
import LoginNavbar from "./customComponents/loginNav";
import { auth, currentUser } from '@clerk/nextjs/server';
import { redirect } from "next/navigation";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// revalidate

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Toaster />
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}

