import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./customComponents/footer";
import Navbar from "./customComponents/navbar";
import { revalidate } from "./(roots)/page";
import { Toaster } from "react-hot-toast";
import { Separator } from "@/components/ui/separator";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

revalidate

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Toaster  />
      <Navbar />
      <Separator className=" border-[1px] border-black"/>
      {children}
      <Footer />
      </body>
    </html>
  );
}
